[tool.poetry]
name = "redbot"
version = "0.1.0"
description = "一个使用 Graia Ariadne 搭建的 QQ 机器人"
authors = ["Redlnn <w731347477@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Redlnn/redbot"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
aiodns = "^3.0.0"
aiofile = "^3.7.4"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
dnspython = "^2.1.0"
gitpython = "^3.1.24"
graia-ariadne = {version = "^0.5.0b2", allow-prereleases = true}
graia-broadcast = "^0.14.4"
graia-saya = "^0.0.13"
graia-scheduler = "^0.0.6"
httpx = "^0.21.1"
jieba = "^0.42.1"
loguru = "^0.5.3"
mctools = "^1.1.2"
numpy = "^1.21.5"
orjson = "^3.6.5"
peewee = "^3.14.8"
pillow = "^8.4.0"
psutil = "^5.9.0"
pydantic = "^1.8.2"
pymysql = "^1.0.2"
pyyaml = "^6.0"
regex = "^2021.11.10"
requests = "^2.26.0"
wordcloud = "^1.8.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
isort = {extras = ["requirements_deprecated_finder"], version = "^5.10.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.poetry.source]]
name = "aliyun"
default = false
url = "https://mirrors.aliyun.com/pypi/simple/"

[[tool.poetry.source]]
name = "tencent-cloud"
default = false
url = "https://mirrors.cloud.tencent.com/pypi/simple"

[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"
