[tool.poetry]
name = "redbot"
version = "0.1.0"
description = ""
authors = ["Redlnn <w731347477@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dnspython = "^2.1.0"
graia-ariadne = {version = "^0.4.0", allow-prereleases = true}
graia-saya = "^0.0.13"
httpx = "^0.21.0"
loguru = "^0.5.3"
mctools = "^1.1.2"
numpy = "^1.21.4"
peewee = "^3.14.8"
pillow = "^8.4.0"
pymysql = "^1.0.2"
pyyaml = "^6.0"
regex = "^2021.11.10"
requests = "^2.26.0"
graia-scheduler = "^0.0.6"
graia-broadcast = "^0.14.1"
gitpython = "^3.1.24"
psutil = "^5.8.0"
wordcloud = "^1.8.1"
jieba = "^0.42.1"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0.1"
autopep8 = "^1.6.0"
devtools = "^0.8.0"
isort = {extras = ["requirements_deprecated_finder"], version = "^5.10.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"
