[tool.poetry]
name = "redbot"
version = "0.1.0"
description = "一个使用 Graia Ariadne 搭建的 QQ 机器人"
authors = ["Redlnn <w731347477@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Redlnn/redbot"

[tool.poetry.dependencies]
python = "^3.10"
aiodns = "^3.0.0"
aiofile = "^3.8.1"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
aio-mc-rcon = "^3.1.1"
fastapi = "^0.79.0"
gitpython = "^3.1.27"
graia-ariadne = {extras = ["full"], version = "^0.8.0"}
httpx = "^0.23.0"
jieba = "^0.42.1"
loguru = "^0.6.0"
lxml = "^4.9.1"
numpy = "^1.23.2"
orjson = "^3.7.11"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pillow = "^9.2.0"
psutil = "^5.9.0"
pydantic = "^1.9.2"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
sqlalchemy = {extras = ["asyncmy", "aiosqlite"], version = "^1.4.40"}
sqlmodel = "^0.0.6"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
wordcloud = "^1.8.2"

[tool.poetry.dev-dependencies]
black = ">=22.3.0"
flake8 = ">=5.0.3"
isort = {extras = ["requirements_deprecated_finder"], version = ">=5.10.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[tool.poetry.source]]
name = "aliyun"
default = false
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"
