[tool.poetry]
name = "redbot"
version = "0.1.0"
description = "一个使用 Graia Ariadne 搭建的 QQ 机器人"
authors = ["Redlnn <w731347477@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Redlnn/redbot"

[tool.poetry.dependencies]
python = "^3.10"
aiodns = "^3.0.0"
aiofile = "^3.7.4"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
aio-mc-rcon = "^3.1.1"
gitpython = "^3.1.27"
graia-ariadne = {extras = ["full"], version = "^0.6.10", allow-prereleases=true}
httpx = "^0.22.0"
jieba = "^0.42.1"
loguru = "^0.6.0"
lxml = "^4.8.0"
numpy = "^1.22.3"
orjson = "^3.6.7"
pillow = "^9.0.1"
psutil = "^5.9.0"
pydantic = "^1.9.0"
pyyaml = "^6.0"
regex = "^2022.3.2"
sqlalchemy = {extras = ["asyncmy", "aiosqlite"], version = "^1.4.32"}
sqlmodel = "^0.0.6"
wordcloud = "^1.8.1"
alembic = "^1.7.7"

[tool.poetry.dev-dependencies]
black = ">=21.1.0"
flake8 = ">=4.0.1"
isort = {extras = ["requirements_deprecated_finder"], version = ">=5.10.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[tool.poetry.source]]
name = "aliyun"
default = false
url = "https://mirrors.aliyun.com/pypi/simple/"

[[tool.poetry.source]]
name = "tencent-cloud"
default = false
url = "https://mirrors.cloud.tencent.com/pypi/simple"

[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"
